version: '3.7'

services:

  ereader:
    container_name: ereader
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - 'frontend-bookclub:/app'
      - 'node-modules:/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

volumes:
  frontend-bookclub:
  node-modules: